name: Release Rust App

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:

    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable


    - name: Build Release
      run: cargo build --release


    - name: Package Windows
      if: matrix.os == 'windows-latest'
      run: |
        mkdir release
        copy target\release\*.exe release\


    - name: Package Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        mkdir release
        cp target/release/* release/


    - name: Upload Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          release/*